text_ignore = []

# ISO 639-1
target_language_code = "ja-JP"

# ISO 639-1
language_codes_display = ["en"]

language_codes_ignore = ["ja"]

display_code = '''
writeln('<!DOCTYPE html>', 'w')
writeln('<html lang="jp">')
writeln('<head>')
writeln('    <meta charset="UTF-8">')
writeln('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
writeln('    <title>Document</title>')
writeln('    <style>')
writeln('        body {')
writeln('            font-size: 24px;')
writeln('        }')
writeln('    </style>')
writeln('</head>')
writeln('<body>')
writeln('    <div style="position: relative;">')
for result in results:
    writeln(f'<div style="left: {result.left}px; top: {result.top}px; width: {result.right - result.left}px; position: absolute; background-color: aliceblue;">{result.translated}</div>')
writeln('    </div>')
writeln('</body>')
writeln('</html>')
'''

google_translate_api_project_name = "projects/rosy-hope-368115"